# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: windows-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v2

    # Runs a single command using the runners shell


    # Runs a set of commands using the runners shell
    - name: Run a multi-line script
      run: |
        curl.exe -o DesigniteConsole.zip "http://www.designite-tools.com/download/DesigniteConsole.zip"
        powershell.exe -nologo -noprofile -command "& { Add-Type -A 'System.IO.Compression.FileSystem'; [IO.Compression.ZipFile]::ExtractToDirectory('DesigniteConsole.zip','.');}"
        
        cd DesigniteConsole 
        git clone https://github.com/mgregory22/Organizer.git

        
        .\DesigniteConsole.exe "Organizer.sln" -X "./test.xml"
        curl -X PUT -H"Authorization: Token 57f056d143cce8ce7fe9a212cd68609208ac471e" -H "username: vishvajeet10gfs@gmail.com" -H "Content-Type: multipart/form-data" -H "Repository-link: https://qscored.com/" --url "https://qscored.com/api/upload/file.xml?is_open_access=on&version=121&project_name=NorthWind" -F "file=@test.xml" 
        
        dir
        
